/* SoC level DTS fixup file */

#define DT_NUM_IRQ_PRIO_BITS	DT_ARM_V7M_NVIC_E000E100_ARM_NUM_IRQ_PRIORITY_BITS

#define DT_ADC_0_NAME			DT_NORDIC_NRF_SAADC_ADC_0_LABEL

#ifdef DT_NORDIC_NRF_UART_UART_0_LABEL
#define DT_UART_0_NAME			DT_NORDIC_NRF_UART_UART_0_LABEL
#else
#define DT_UART_0_NAME			DT_NORDIC_NRF_UARTE_UART_0_LABEL
#endif

#define DT_UART_1_NAME			DT_NORDIC_NRF_UARTE_UART_1_LABEL

#define DT_FLASH_DEV_NAME		DT_NORDIC_NRF52_FLASH_CONTROLLER_0_LABEL

#if defined(CONFIG_QSPI_FLASH_NRF)
  #define DT_SERIAL_FLASH_DEV_NAME	DT_NORDIC_NRF_QSPI_FLASH_CONTROLLER_40029000_LABEL
  #define DT_SERIAL_FLASH_ADDRESS	DT_SERIAL_FLASH_12000000_BASE_ADDRESS
  #define DT_SERIAL_FLASH_SIZE		DT_SERIAL_FLASH_12000000_SIZE

  #define DT_QSPI_FLASH_CSN_PIN		DT_NORDIC_NRF_QSPI_FLASH_CONTROLLER_40029000_CSN_PIN
  #define DT_QSPI_FLASH_SCK_PIN		DT_NORDIC_NRF_QSPI_FLASH_CONTROLLER_40029000_SCK_PIN
  #define DT_QSPI_FLASH_IO0_PIN		DT_NORDIC_NRF_QSPI_FLASH_CONTROLLER_40029000_IO_PINS_0
  #define DT_QSPI_FLASH_IO1_PIN		DT_NORDIC_NRF_QSPI_FLASH_CONTROLLER_40029000_IO_PINS_1
  #define DT_QSPI_FLASH_IO2_PIN		DT_NORDIC_NRF_QSPI_FLASH_CONTROLLER_40029000_IO_PINS_2
  #define DT_QSPI_FLASH_IO3_PIN		DT_NORDIC_NRF_QSPI_FLASH_CONTROLLER_40029000_IO_PINS_3
  #define DT_QSPI_FLASH_IRQ	 	DT_NORDIC_NRF_QSPI_FLASH_CONTROLLER_40029000_IRQ_0
  #define DT_QSPI_FLASH_IRQ_PRI		DT_NORDIC_NRF_QSPI_FLASH_CONTROLLER_40029000_IRQ_0_PRIORITY

  #if defined(DT_NORDIC_NRF_QSPI_FLASH_CONTROLLER_40029000_QSPI_MAX_FREQUENCY)
  #define DT_QSPI_FLASH_QSPI_FREQ_0	DT_NORDIC_NRF_QSPI_FLASH_CONTROLLER_40029000_QSPI_MAX_FREQUENCY
  #else
  #define DT_QSPI_FLASH_QSPI_FREQ_0	32000000
  #endif
#endif

#define DT_GPIO_P0_DEV_NAME		DT_NORDIC_NRF_GPIO_GPIO_0_LABEL
#define DT_GPIO_P1_DEV_NAME		DT_NORDIC_NRF_GPIO_GPIO_1_LABEL

#define DT_I2C_0_NAME			DT_NORDIC_NRF_I2C_I2C_0_LABEL
#define DT_I2C_1_NAME			DT_NORDIC_NRF_I2C_I2C_1_LABEL

#define DT_SPI_0_NAME			DT_NORDIC_NRF_SPI_SPI_0_LABEL
#define DT_SPI_1_NAME			DT_NORDIC_NRF_SPI_SPI_1_LABEL
#define DT_SPI_2_NAME			DT_NORDIC_NRF_SPI_SPI_2_LABEL
#define DT_SPI_3_NAME			DT_NORDIC_NRF_SPI_SPI_3_LABEL

#define DT_WDT_0_NAME			DT_NORDIC_NRF_WATCHDOG_WDT_0_LABEL

/* End of SoC Level DTS fixup file */
